# This is a basic workflow to help you get started with Actions

name: build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-16.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: install
        run: |
          sudo apt update
          sudo apt install g++ cmake libboost-program-options-dev libyaml-cpp-dev clang-tidy clang-format python3-matplotlib libompl-dev libeigen3-dev
          python3 -m pip install -r requirements.txt

      - name: make
        run: |
          mkdir build 
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make -j8

      - name: run code
        run: |
          cd build
          ./planner -i ../maps/random.yaml -o output.yaml
